name:                redbook
version:             0.1.0.0
github:              "githubuser/redbook"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/redbook#readme>

dependencies:
- base >= 4.7 && < 5
- GLUT == 2.7.0.14
- ObjectName == 1.1.0.1
- bytestring == 0.10.8.2
- ply-loader == 0.5.0
- vector == 0.12.0.1
- wavefront == 0.7.1.3
- GLURaw == 2.0.0.4
- gl == 0.8.0
- linear == 1.20.8
library:
  source-dirs: src

executables:
  redbook-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - redbook

tests:
  redbook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - redbook
